import type { Applicant } from './types';

export const applicants: Applicant[] = [
  {
    id: 'APL-001',
    name: 'John Doe',
    avatar: '1',
    email: 'john.doe@example.com',
    loanType: 'Home',
    loanAmount: 250000,
    loanTenure: 240,
    creditScore: 780,
    incomeToEmiRatio: 0.35,
    branch: 'New York',
    status: 'Approved',
    applicationDate: '2023-10-15',
    eligibilityScore: 88,
  },
  {
    id: 'APL-002',
    name: 'Jane Smith',
    avatar: '2',
    email: 'jane.smith@example.com',
    loanType: 'Personal',
    loanAmount: 20000,
    loanTenure: 36,
    creditScore: 650,
    incomeToEmiRatio: 0.5,
    branch: 'London',
    status: 'Rejected',
    applicationDate: '2023-10-12',
    eligibilityScore: 55,
  },
  {
    id: 'APL-003',
    name: 'Samuel Green',
    avatar: '3',
    email: 'samuel.green@example.com',
    loanType: 'Auto',
    loanAmount: 35000,
    loanTenure: 60,
    creditScore: 710,
    incomeToEmiRatio: 0.4,
    branch: 'Tokyo',
    status: 'Pending',
    applicationDate: '2023-10-20',
    eligibilityScore: 72,
  },
  {
    id: 'APL-004',
    name: 'Emily White',
    avatar: '4',
    email: 'emily.white@example.com',
    loanType: 'Home',
    loanAmount: 320000,
    loanTenure: 360,
    creditScore: 810,
    incomeToEmiRatio: 0.3,
    branch: 'New York',
    status: 'Approved',
    applicationDate: '2023-09-28',
    eligibilityScore: 92,
  },
  {
    id: 'APL-005',
    name: 'Michael Brown',
    avatar: '5',
    email: 'michael.brown@example.com',
    loanType: 'Personal',
    loanAmount: 15000,
    loanTenure: 24,
    creditScore: 690,
    incomeToEmiRatio: 0.45,
    branch: 'London',
    status: 'Pending',
    applicationDate: '2023-10-21',
    eligibilityScore: 68,
  },
  {
    id: 'APL-006',
    name: 'Jessica Jones',
    avatar: '6',
    email: 'jessica.jones@example.com',
    loanType: 'Auto',
    loanAmount: 28000,
    loanTenure: 48,
    creditScore: 620,
    incomeToEmiRatio: 0.55,
    branch: 'Tokyo',
    status: 'Rejected',
    applicationDate: '2023-10-05',
    eligibilityScore: 48,
  },
   {
    id: 'APL-007',
    name: 'David Wilson',
    avatar: '7',
    email: 'david.wilson@example.com',
    loanType: 'Home',
    loanAmount: 450000,
    loanTenure: 360,
    creditScore: 790,
    incomeToEmiRatio: 0.32,
    branch: 'New York',
    status: 'Pending',
    applicationDate: '2023-10-22',
    eligibilityScore: 90,
  },
  {
    id: 'APL-008',
    name: 'Sarah Miller',
    avatar: '8',
    email: 'sarah.miller@example.com',
    loanType: 'Personal',
    loanAmount: 25000,
    loanTenure: 48,
    creditScore: 720,
    incomeToEmiRatio: 0.38,
    branch: 'London',
    status: 'Approved',
    applicationDate: '2023-10-01',
    eligibilityScore: 78,
  },
];
